CREATE TABLE `closed_sales` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customerName` varchar(255) NOT NULL,
	`customerEmail` varchar(320),
	`customerPhone` varchar(20) NOT NULL,
	`installAddress` text NOT NULL,
	`postalAddress` text,
	`nmi` varchar(20),
	`meterNumber` varchar(50),
	`currentRetailer` varchar(100),
	`distributor` varchar(100),
	`existingSolar` enum('yes','no') DEFAULT 'no',
	`propertyType` enum('house','townhouse','unit','commercial') DEFAULT 'house',
	`roofType` enum('tile','colorbond','flat','klip-lok','other') DEFAULT 'colorbond',
	`phases` enum('1-phase','2-phase','3-phase') DEFAULT '1-phase',
	`systemSizeDc` decimal(6,2),
	`systemSizeAc` decimal(6,2),
	`panelBrand` varchar(255),
	`panelModel` varchar(255),
	`panelQuantity` int,
	`panelWattage` int,
	`inverterBrand` varchar(255),
	`inverterModel` varchar(255),
	`inverterQuantity` int DEFAULT 1,
	`batteryBrand` varchar(255),
	`batteryModel` varchar(255),
	`batteryCapacityKwh` decimal(6,2),
	`batteryQuantity` int,
	`optimisers` varchar(255),
	`mountingType` enum('roof','ground','tilt-frame') DEFAULT 'roof',
	`exportLimitKw` decimal(5,2),
	`evCharger` varchar(255),
	`hotWaterSystem` varchar(255),
	`additionalProducts` text,
	`totalContractPrice` decimal(10,2) NOT NULL,
	`depositAmount` decimal(10,2),
	`depositPaid` enum('yes','no') DEFAULT 'no',
	`depositDate` bigint,
	`paymentMethod` enum('cash','finance','green-loan','interest-free','mixed') DEFAULT 'cash',
	`financeProvider` varchar(255),
	`financeAmount` decimal(10,2),
	`financeTerm` varchar(100),
	`stcRebateValue` decimal(10,2),
	`numberOfStcs` int,
	`pricePerWatt` decimal(6,2),
	`balanceDue` decimal(10,2),
	`paymentSchedule` text,
	`contractSignedDate` bigint NOT NULL,
	`contractDocumentUrl` text,
	`coolingOffExpiry` bigint,
	`cecInstaller` varchar(255),
	`cecDesigner` varchar(255),
	`warrantyWorkmanshipYears` int DEFAULT 5,
	`warrantyPanelProductYears` int DEFAULT 25,
	`warrantyInverterYears` int DEFAULT 10,
	`warrantyBatteryYears` int DEFAULT 10,
	`roofOrientation` varchar(255),
	`roofPitch` int,
	`shadingAssessment` varchar(255),
	`switchboardCondition` enum('good','needs-upgrade','asbestos') DEFAULT 'good',
	`switchboardUpgrade` enum('yes','no') DEFAULT 'no',
	`cableRunMetres` int,
	`trenchingRequired` enum('yes','no') DEFAULT 'no',
	`annualProductionEstimate` int,
	`energyOffsetPercent` int,
	`dealOwner` varchar(255),
	`leadSource` varchar(100),
	`closedWonReason` text,
	`daysInPipeline` int,
	`proposalsSent` int,
	`referralSource` varchar(255),
	`projectStatus` enum('contract-signed','cooling-off','pre-installation','dnsp-applied','dnsp-approved','permit-applied','permit-approved','scheduled','installation','inspection','commissioning','pto-received','complete') NOT NULL DEFAULT 'contract-signed',
	`scheduledInstallDate` bigint,
	`installCompleteDate` bigint,
	`ptoDate` bigint,
	`finalPaymentReceived` enum('yes','no') DEFAULT 'no',
	`notes` text,
	`leadPhone` varchar(20),
	`userId` int,
	`createdAt` bigint NOT NULL,
	`updatedAt` bigint NOT NULL,
	CONSTRAINT `closed_sales_id` PRIMARY KEY(`id`)
);
